--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NorixDevelopment/GrantGUI
build-by-default: true
branches:
- main
projects:
  GrantGUI:
    path: ""
    icon: "resources/GrantGUI.gif"
    libs:
    - src: muqsit/invmenu/InvMenu
        version: ^4.1.1
        branch: master
...
