--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NorixDevelopment/GrantGUI
build-by-default: true
branches:
- main
projects:
  GrantGUI:
    path: ""
    icon: "GrantGUI/icon.gif"
    libs:
      - src: libs/muqsit/InvMenu/InvMenu
        version: ^4.1.1
...
