--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NorixDevelopment/GrantGUI
build-by-default: true
branches:
- main
projects:
  GrantGUI:
    path: /
    icon: "icon.gif"
    - src: muqsit/invmenu/InvMenu
        version: ^4.1.1
        branch: master
...
